backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Year", name: "year", widget: "string", default: "2024"}
      - {label: "Type", name: "type", widget: "select", options: ["video", "photo"]}
      - {label: "Thumbnail", name: "thumb", widget: "image"}
